Repository KvNGCzA/Hello-Books-BE, pull requests merged in 2019-05, with the labels that each got.

#4 166214081 add hound badge to readme.md file
  README.md
Labels: Under Review

#2 166267668 setup node and express
  package-lock.json
  package.json
  server/index.js
Labels: Under Review

#6 #166267831 Set up Babel
  .babelrc
  package-lock.json
  package.json
Labels: TTL Review

#8 #166214083 Setup swagger documentation
  package-lock.json
  package.json
  server/index.js
  swagger.json
Labels: TTL Review

#11 #166214082 Database setup
  .env.sample
  .eslintrc.json
  .sequelizerc
  package.json
  server/database/config/config.js
  server/database/migrations/index.js
  server/database/models/index.js
  server/database/seeders/index.js
Labels: PEER-REVIEW

#12 #166214077 Configure Travis CI build
  .gitignore
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: TTL Review

#16 #166314469 Implement Book and Author model feature
  server/database/migrations/20190529204216-create-author.js
  server/database/migrations/20190529204542-create-books.js
  server/database/migrations/index.js
  server/database/models/author.js
  server/database/models/books.js
  server/database/seeders/index.js
Labels: TTL Review

#17 #166214086 deploy base heroku application
  Procfile
  package.json
Labels: PEER-REVIEW

#14 #166313092 create user model
  package-lock.json
  package.json
  server/database/migrations/20190530205044-create-users.js
  server/database/models/index.js
  server/database/models/users.js
  server/database/seeders/20190530205345-demo-users.js
  server/index.js
  test/index-test.js
Labels: PEER-REVIEW

#19 #166313415 create roles model
  server/database/migrations/20190530141523-create-roles.js
  server/database/models/roles.js
  server/database/seeders/20190529165248-roles.js
Labels: TTL Review

#20 #166374539 Implement Favourites model
  package-lock.json
  server/database/migrations/20190531104456-create-favourites.js
  server/database/models/author.js
  server/database/models/favourites.js
  server/database/models/users.js
Labels: TTL Review

#21 166325007 Create Followers Model
  server/database/migrations/20190531114337-create-followers.js
  server/database/models/followers.js
  server/database/models/users.js
  server/database/seeders/20190530205345-demo-users.js
  server/database/seeders/20190531115138-demo-followers.js
Labels: TTL Review

#18 #166214085 integrate coveralls code climate
  README.md
  coveralls.yml
  package-lock.json
  package.json
Labels: TTL Review
